apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-back-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-mgmt-mysql-back-dep
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: user-mgmt-mysql-back-dep
    spec:
      containers:
        - name: user-mgmt-mysql
          image: mysql:5.6
          envFrom: 
          - secretRef:
              name: user-mgmt-mysql-var
          ports:
            - containerPort: 3306
              name: mysqlport
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
            - name: user-mgmt-mysql-script   #config map
              mountPath: docker-entrypoint-initdb.d #https://hub.docker.com/_/mysql Refer Initializing a fresh instance
         
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: user-mgmt-mysql-pv      #pv name
        - name: user-mgmt-mysql-script  # config map to create requraired DB scema 
          configMap:
            name: user-mgmt-mysql-configMap