apiVersion: v1
kind: Service 
metadata:
 name: user-mgmt-app-service

spec:
  type: NodePort
  selector: 
    app: user-mgmt-front-app    #mapped to user mgmt app
  ports:
    - port: 8095
      targetPort: 8095
      nodePort: 30881
 