apiVersion: v1
kind: Servive 
metadata:
 name: user-mgmt-mysql-back-service

spec:
  type: NodePort
  selector: 
    app: user-mgmt-front-app    #mapped to user mgmt app
  ports:
    - port: 8095
      targetPort: 8095
 