apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user_mgmt_mysql_pv  #will be used in mysql Deployment file

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: user_mgmt_mysql_sc  # from storage class
  resources:
    requests:
      storage: 5Gi
